### ISSUE TITLE
KImg Component

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri-design-system#368]
# Overview
The `KImg` component displays images and provides additional functionality to manipulate the images such as
- Image aspect ratio
- Image scaling

# Motivation

Inspired by thumbnails to a large extent so it should satisfy our needs for working with them, but should be usable as a general image component as well.

# Interface

### Props

| Name | Description | Type | Default | Required |
| - | - | - | - | - |
| `src` | Sets the image path | `String` | `null` | `false` |
| `altText` | Alternate text for the image. This is required and will throw a warning when its not provided(empty) unless `isDecorative` is `true` | `String` |  | `true` |
| `isDecorative` | Sets the image as decorative. This sets the `alt` image property to an empty string. | `Boolean` | `false` | `false` |
| `height` | Sets the height for the component. | `Number`, `String` | `undefined` | `false` |
| `width` | Sets the width for the component. | `Number`, `String` | `undefined` | `false` |
| `maxHeight` | Sets the maximum height for the component. | `Number`, `String` | `undefined` | `false` |
| `minHeight` | Sets the minimum height for the component. | `Number`, `String` | `undefined` | `false` |
| `maxWidth` | Sets the maximum width for the component. | `Number`, `String` | `undefined` | `false` |
| `minWidth` | Sets the minimum width for the component. | `Number`, `String` | `undefined` | `false` |
| `aspectRatio` | Sets the ratio of the width(w) to the height(h) of the image container. The required format is `w:h`, otherwise `<KImg>` will show an error. | `String` | `undefined` | `false` |
| `scaleType` | Specifies how the image should be scaled within the container. Can be one of `centerInside`, `contain` or, `fitXY`. See below the scale types to be supported.  | `String` | `contain` | `false` |
| `placeholderColor` | Sets color for the image placeholder | `String` | `$themePalette.grey.v_200` | `false` |
| `borderRadius` | Sets tne boarder radius of the image or placeholder | `Number` | `undefined` | `false` |
| `appearanceOverrides` | Overrides styling of the component | `Object` | `null` | `false` |
| `kolibriFly` | Renders the Kolibri fly logo into the `KImg`. This overrides the `src` specified | `Boolean` | `false` | `false` | 

#### `scaleType`

| Type | Description | Illustration |
| - | - | - |
| `centerInside` | Scale image uniformly, maintaining its `aspectRatio` so that both its `width` and `height` are equal to or less than the corresponding dimension of the `<KImg>`. This may result into letterboxing | ![image](https://user-images.githubusercontent.com/5203639/190570907-615435b0-d877-46bd-9693-7b63e264ec2f.png) |
| `contain` | Scale image, maintaining its(original or set) `aspectRatio`, but also ensuring that it fits entirely inside the `<KImg>`. At least one axis (X or Y) will fit exactly. The result is centered inside `<KImg>`. This may result into letterboxing | ![image](https://user-images.githubusercontent.com/5203639/190571642-c3cdd487-2c41-4a1b-b6d3-2fa8ac19dc95.png) |
| `fitXY` | Scale X and Y independently, so that the image matches `<KImg>` exactly. This may change the `aspectRatio`, distorting the image. This never results into letterboxing | ![image](https://user-images.githubusercontent.com/5203639/190574099-5805d88e-8501-48a9-9351-5cde27143950.png) |

This is inspired by Android's [`ImageView.ScaleType`](https://developer.android.com/reference/android/widget/ImageView.ScaleType)

#### `height`, `width`, `maxtHeight`, `minHeight`, `maxHeight`, `minHeight`
- `px` units will be used for type `number`, otherwise you can specify your preferred unit(e.g. `12em`, `3rem`)

### Events
| Name | Description |
| - | - |
| `error` | Emitted when an error is encountered while loading the image specified in `src` |

### Slots
| Name | Description |
| - | - |
| `placeholder` | A slot for an image placeholder. This is centered within the image area |
| `default` | The default slot. This can be styled independently |

# Epic issues
1. https://github.com/learningequality/kolibri-design-system/issues/369
2. https://github.com/learningequality/kolibri-design-system/issues/370
3. https://github.com/learningequality/kolibri-design-system/issues/371
4. https://github.com/learningequality/kolibri-design-system/issues/374
5. [optional] https://github.com/learningequality/kolibri-design-system/issues/372
6. [optional] https://github.com/learningequality/kolibri-design-system/issues/373

# Epic acceptance criteria

- [ ] Epic issues 1-4 are finished
- [ ] `KImg` is responsive by default (When its container scales down, it scales down too. Size props need to be used to change this behavior, for example, setting both `width` and `height` to fixed pixel values)
- [ ] It is tested visually and whenever relevant also by means of unit tests
- [ ] `KImg` is tested and optimized performance-wise, especially if there is any custom JavaScript DOM manipulation (there should be the certainty that it doesn't cause any bottlenecks as it may be used in large quantities on one page)
- [ ] Changelog is updated

# Out of scope/Optional
- Epic issues 5-6
- Multiple image sources for various screens sizes
- Lazy image loading for non-critical images

# Related

- [Notion project page](https://www.notion.so/learningequality/Spec-KImg-component-6fe9ac1fef764630a587fe1f9b805e7f)
- https://github.com/learningequality/kolibri-design-system/issues/23
- https://github.com/learningequality/kolibri/issues/7139

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/538
