### ISSUE TITLE
KImg: Implement the basic component

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#369]
## Summary

Implement the KImg component with the following props
- `src`
- `altText`
- `isDecorative`
- `height`
- `width`
- `maxHeight`
- `minHeight`
- `maxWidth`
- `minWidth`

and the default slot.

See the epic issue for props and slot definitions.

## Epic

- https://github.com/learningequality/kolibri-design-system/issues/368

## Acceptance criteria

- [ ] The component contains all the props specified above and the default slot
- [ ] Setting the `src` prop renders an image in the component
- [ ] The image is rendered as `<img>` (not as the background image)
- [ ] Setting the `altText` is mandatory and throws a warning when not provided(empty) unless `isDecorative` is `true`
- [ ] Setting `isDecorative` to `true` specifies an empty string to the `alt` image property and `altText` becomes optional so no warning is thrown and `altText` is overridden to the empty string when provided.
- [ ] Setting `height`, `width`, `maxHeight`, `minHeight`, `maxWidth`, `minWidth` alters the dimensions of the component

## Linked issues

- **Blocking**
  - https://github.com/learningequality/kolibri-design-system/issues/370
  - https://github.com/learningequality/kolibri-design-system/issues/371
  - https://github.com/learningequality/kolibri-design-system/issues/372
  - https://github.com/learningequality/kolibri-design-system/issues/373
  - https://github.com/learningequality/kolibri-design-system/issues/374

**Comment by nucleogenesis** [comment]
Closing as @MisRob has reviewed
