### ISSUE TITLE
KImg: Add 'appearanceOverrides'

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#371]
## Summary

`KImg` accepts the Vue dynamic styles object, for example

```javascript
{
   width: '100%',
   textDecoration: 'none',
   color: $themeTokens.text
}
```

via `appearanceOverrides` prop, which will override the component's styling

## Epic

- https://github.com/learningequality/kolibri-design-system/issues/368

## Acceptance criteria

- [ ] Using `appearanceOverrides` modifies the appearance of the component
- [ ] Its attributes always take precedence over any specified styling (e.g. internal component's styles, styles calculated from props, ...) 
- [ ] Documentation is updated with all new features. Contains guidance and examples whenever relevant.

## Linked issues

- **Blocked by**
  - https://github.com/learningequality/kolibri-design-system/issues/369
  - https://github.com/learningequality/kolibri-design-system/issues/370

- **Blocking**
  - https://github.com/learningequality/kolibri-design-system/issues/374

**Comment by EshaanAgg** [comment]
Hi! I want to work on this issue. 
Since the Kolibri team is on a break for the holidays, I am taking the liberty to work on the issue without being explicitly assigned. Hope that's okay!
