### ISSUE TITLE
KImg: Polish documentation

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri-design-system#374]
## Summary

Even though the documentation for `KImg` should exist, it'll be put together gradually (and presumably by more devs). This issue is to polish it to ensure consistency and good organization and wording.

## Epic

- https://github.com/learningequality/kolibri-design-system/issues/368

## Acceptance criteria

- [ ] Contains a summary, examples, and guidelines that are created in cooperation with the design team
- [ ] All props are documented
- [ ] All slots are documented
- [ ] All events are documented

## Linked issues

- **Blocked by**
  - https://github.com/learningequality/kolibri-design-system/issues/369
  - https://github.com/learningequality/kolibri-design-system/issues/370
  - https://github.com/learningequality/kolibri-design-system/issues/371

**Comment by MisRob** [comment]
@jtamiace comment:
> i think one thing we can add for design/UX guidelines is an example of how these props and settings are currently applied and why. using thumbnails as the example since it’s the most common use now - why we use the current scaling/aspect ratio settings for it, and the UX considerations that affect those decisions

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri-design-system/pull/538
