### ISSUE TITLE
Upgrade to NodeJS 18

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-design-system#439]
## Blocks

https://github.com/learningequality/kolibri-design-system/issues/510

## Summary

KDS still uses NodeJS 12 which is no longer maintained or supported. At some point in the future, doubtless Github Actions will cease supporting this, which will cause our Github Actions to break.

We should upgrade to use NodeJS 16 which will require the following sequence of steps:

```[tasklist]
### Tasks
- [ ] https://github.com/learningequality/kolibri/pull/9698
- [ ] https://github.com/learningequality/kolibri/pull/12722
- [ ] https://github.com/learningequality/kolibri/issues/8454
- [ ] Remove dependency on kolibri-tools and replace with the newly independent kolibri-formatting-tools or whatever the name ends up being
- [ ] In conjunction with this update the NodeJS version to the version required for the formatting tools (currently 16, but will become 18 in the future)
- [ ] Upgrade to VueJS 2.7
- [ ] Upgrade any build dependencies by the smallest version increment possible to have compatibility with the new NodeJS version (to avoid completely breaking the build system or requiring a more holistic upgrade)
- [ ] https://github.com/learningequality/kolibri/issues/10636
```

**Comment by MisRob** [comment]
When this is ready, we will also need to update this Netlify settings

![Screenshot from 2023-10-18 17-53-23](https://github.com/learningequality/kolibri-design-system/assets/13509191/4b9e753c-f5e2-480f-8995-40bd744c1909)

I can do it, let me know when the time comes.

**Comment by rtibbles** [comment]
I just gave this another stab - still seems to be some complexity here, I don't know if the kolibri package separation is needed here, but it may make it simpler at the least.
