### ISSUE TITLE
KCard Component Enhancements

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri-design-system#624]
```[tasklist]
### Tasks
- [x] Add consistence padding around all inner  content area of the` KCard`
- [x] Add  prop` to ` to the router-link i.e passed to `router-link`
- [x] Validate that the heading level is a value between 2 and 6
- [x] Move this validation logic to the BaseCard component if it's applicable to both BaseCard and` KCard.` If the validation is specific to` KCard,` implement it within the `KCard` component. If the validation applies to both BaseCard and` KCard,` move it to the BaseCard
- [x] Change the outermost element of the `KCard `component from `<button>` to` <li>`
- [x] Remove the duplicate link element that wraps the title text within the [`BaseCard `](https://github.com/learningequality/kolibri-design-system/issues/529)component.
- [x] Add a mechanism to allow users to select and copy text content within a clickable area (potentially the entire KCard), even though the entire area is a clickable link.
- [x] Refactor the existing test suite for the` KCard` component to ensure it adequately covers  edge case(s).
- [x] When a user tabs to a KCard and presses Enter, it should open the card's intended action (e.g., navigate to a linked page)
```
