### ISSUE TITLE
Make changelog checks more robust

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri-design-system#760]
<img height="20px" src="https://i.imgur.com/c7hUeb5.jpeg">

❌ **This issue is not open for contribution. Visit <a href="https://learningequality.org/contributing-to-our-open-code-base/" target="_blank">Contributing guidelines</a>** to learn about the contributing process and how to find suitable issues.

<img height="20px" src="https://i.imgur.com/c7hUeb5.jpeg">

## Product
KDS.

## Desired behavior

Would be helpful to update our [Check Changelog](https://github.com/learningequality/kolibri-design-system/blob/d3d40d2b2ec63e51f509b0eb5221a9fa2770edb3/.github/workflows/changelog.yml) and [Update Changelog](https://github.com/learningequality/kolibri-design-system/blob/d3d40d2b2ec63e51f509b0eb5221a9fa2770edb3/.github/workflows/update_changelog.yml) workflows to make them more robust.

```[tasklist]
### Tasks
- [ ] Update the `Check PR for Changelog` workflow to check that every field of a changelog item exist, that its not empty and that they are different from the "default" values written in the [PR Template](https://github.com/learningequality/kolibri-design-system/blob/d3d40d2b2ec63e51f509b0eb5221a9fa2770edb3/.github/pull_request_template.md#L26).
- [ ] Update the `Check PR for Changelog` workflow to make sure that the `<!-- [DO NOT REMOVE-USED BY GH ACTION] CHANGELOG START -->` and `<!-- [DO NOT REMOVE-USED BY GH ACTION] CHANGELOG END -->` flags are present in the PR description.
- [ ] Find a way to separate multiple changelog items and have them render nicely in the PR description (tbd).
- [ ] Update the `Update Changelog` workflow to ignore any line that does not correspond to any of the changelog item fields.
```
## Possible Tradeoffs

We will probably need to create script files to avoid having too much logic code written inside the gh workflow file.

**Comment by RONAK-AI647** [comment]
**Hey @AlexVelezLl ,I wanna work on this issue .Will you give an opportunity.******

**Comment by AllanOXDi** [comment]
Hi @RONAK-AI647 I have assigned it to you- Thanks for contributing

**Comment by RONAK-AI647** [comment]
@AlexVelezLl @AllanOXDi Raised a PR ,kindly review .

**Comment by AlexVelezLl** [comment]
Thank you @RONAK-AI647! We will take a look

**Comment by MisRob** [comment]
Hi @RONAK-AI647, I wanted to mention that [Learning Equality will be closed from December 23 to January 5](https://github.com/learningequality/kolibri/discussions/12956).

**Comment by MisRob** [comment]
@RONAK-AI647 has made some good progress in https://github.com/learningequality/kolibri-design-system/pull/885, but we closed due to inactivity. To resolve this issue, the referenced PR can be used as basis + including review feedback from @rtibbles.
